ktor:
  application:
    modules:
      - br.com.ApplicationKt.module
  deployment:
    port: 8080

buscamed:
  gcp:
    project_id: ${GCP_PROJECT_ID}
    service_audience: ${GCP_SERVICE_AUDIENCE}
    region: ${GCP_REGION}